# Generated by Django 5.0.6 on 2024-07-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('⭐☆☆☆☆', '⭐☆☆☆☆'), ('⭐⭐⭐⭐☆', '⭐⭐⭐⭐☆'), ('⭐⭐⭐☆☆', '⭐⭐⭐☆☆'), ('⭐⭐☆☆☆', '⭐⭐☆☆☆'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], max_length=10),
        ),
    ]
