# Generated by Django 5.0.6 on 2024-07-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('⭐☆☆☆☆', '⭐☆☆☆☆'), ('⭐⭐⭐☆☆', '⭐⭐⭐☆☆'), ('⭐⭐☆☆☆', '⭐⭐☆☆☆'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐'), ('⭐⭐⭐⭐☆', '⭐⭐⭐⭐☆')], max_length=10),
        ),
    ]
